### ISSUE TITLE
Initial `changelogs` only include very last commit messages from packages

### ISSUE THREAD

**Issue by jrson83** [bscotch/jslib#2]
After setting up a new monorepo and merging multiple package related PRs, I tried to generate changelogs the first time, without having any git tags, or released packages. Just a plain version `0.1.0` in every package.json.

I now have the issue, that a changelog for a package only includes the very last commit.

I did separate new features/improvements into separate feature branches, with multiple commits and send a pull request for each branch.

**Commit history**
https://github.com/inertiajs-revamped/inertia/commits/main/

**Config**:
https://github.com/inertiajs-revamped/inertia/blob/main/.scripts/changelogs.mjs

**Output for [core](https://github.com/inertiajs-revamped/inertia/tree/main/packages/core) package**:

```md
# Changelog - @inertiajs-revamped/core

## 0.1.0 (2024-04-16)

### Bug Fixes

- fix `IncomingMessage` type-only import ([737860e](https://github.com/jrson83/changelog-test/commit/43ec1d62d93fef5c0b2a77931626b2873c2db52e) by jrson83)
```

**Output for [react](https://github.com/inertiajs-revamped/inertia/tree/main/packages/react) package**:

```md
# Changelog - @inertiajs-revamped/react

## 0.1.0 (2024-04-16)

### Bug Fixes

- fix `renderToString` type-only import ([737860e](https://github.com/jrson83/changelog-test/commit/d94260ff11fec112438686943bdf8264dbc5367b) by jrson83)
```

---

Is there any way I can fix the output, so I get every commit from the initial commit until now for each package?

So it basically picks up all **4** commits since `git init`:

**Commit history react**:
https://github.com/inertiajs-revamped/inertia/commits/main/packages/react

I also thought it will pickup multiple commit messages I created for each PR for the changelog like here:

**Specific commit react**:
https://github.com/inertiajs-revamped/inertia/commit/5364a6009ce7cfd8d9d67a1a33b714766f48ad41

I'm a bit frustrated because I spent very much time into seperating commits and PRs after I tested how the generator worked, when there was no git tag and no changelog at all. Just a plain version `0.1.0` in every package.json. It worked like expected. I appreciate any help you can provide cause I can't see what I'am doing wrong and I really like the changelog generator :heart_eyes:

**Comment by adam-coster** [comment]
Sorry for the frustration! I didn't know anyone else was even using this besides me 😃

It looks like your message lines start with `* ` rather than immediately starting with the message content, which the pack doesn't expect. It assumes that any line you want included matches `/^(feat|etc)/`.

I haven't touched any of this for a while so I can't remember how it's all set up, I'll do some digging to see if there's a way to make it work with the different syntax you're using.

**Comment by adam-coster** [comment]
It looks like you could create your own version of this function:

https://github.com/bscotch/jslib/blob/49601d7ee8410ba136c5e9014800db09dbf151a8/packages/workspaces/src/changelog.ts#L66

With some different regexes than the ones that function uses by default.

In particular, if you were to change the following option to use a modified version of `conventionalCommitsHeaderPattern`:

https://github.com/bscotch/jslib/blob/49601d7ee8410ba136c5e9014800db09dbf151a8/packages/workspaces/src/changelog.ts#L74

E.g. something like:

```js
/^(\s*\*\s*)?(?<type>[a-z]+?)(\((?<scope>[^)]*)\))?(?<isBreaking>!)?: (?<description>.*)/
```

(Which is the same regex with the beginning modified to allow an optional " * " prefix.)

I think that would do it? I'll have to try it on your commits when I'm back on my computer.

**Comment by jrson83** [comment]
Thanks for the answer, I just noticed that I used the default `branch name` as title of my PRs, which like you said include multiple commit messages starting with `*`.

The title becomes the commit message title, which is in my case e.g.:

`fix/should-intercept` branch becomes:

`Fix/should intercept`

So both are not picked up by the parser.

I wonder if I can try rebase amend with `reword`, then force push. I think I will try this tomorrow and rename the `Fix/should intercept` to conventional commit format and see if it gets picked up by the parser then.

**Comment by jrson83** [comment]
> I'll have to try it on your commits when I'm back on my computer.

That would be awesome. I will now also setup a test repo and report my results if I'm done with testing 😁

**Comment by jrson83** [comment]
@adam-coster from my test I can say your tool is working as expected.

~I think I got the issue on the monorepo because I enabled `Require linear history` in the `Branch protection rule`.~

I created a new repo without linear history you can see here, everything is working as expected:

**Working without linear history**:
https://github.com/jrson83/changelog-non-linear/commits/main/

You can see every single commit in the history and it is not `squashed/merged` like on the other repo. Can you confirm this?

**EDIT**:

After testing again I can say that the issue only occurs when using `Squash and merge` a PR.
When I use `Merge` or `Rebase` the generator is working as intended.

**Comment by adam-coster** [comment]
Ah, interesting. Thanks for following up! I'll got ahead and close this issue.
