### ISSUE TITLE
Unexpected arrangement of the group headings of the changelog

### ISSUE THREAD

**Issue by jrson83** [bscotch/jslib#3]
Hey it's me again :grin:

After building the initial changelogs for the single [packages ](https://github.com/inertiajs-revamped/inertia/tree/main/packages) in my monorepo, I notice that the arrangement of the group headings is sorted alphabetically. The repo has not enabled `Linear History` and I used `Merge` for my PR's.

I have not found any specification related Conventional Commit Changelog heading order, but this issue conventional-changelog/conventional-changelog-config-spec/issues/36, but I also do not know which `changelog conventions` your generator follows.

When looking at the most changelogs using Conventional Commit format, `Features` is the most top heading. I wonder if there is a convention for the heading order, or if it has something todo with the repo setup, or commit order, since when looking at your [changelog](https://github.com/bscotch/jslib/blob/develop/packages/workspaces/CHANGELOG.md), it has the right order.

**Comment by adam-coster** [comment]
I think this is where my sort order is coming from:     

https://github.com/bscotch/jslib/blob/49601d7ee8410ba136c5e9014800db09dbf151a8/scripts/changelogs.mjs#L23

**Comment by jrson83** [comment]
Thank you! I just came up with the simple solution:

```ts
const sortOrder = [
  'Features',
  'Code Refactoring',
  'Bug Fixes',
  'Reverts',
  'Builds',
  'Performance Improvements',
  'Styles',
  'Documentation',
  'Tests',
]

// ....
const groups = Object.keys(version.groups).sort(
  (a, b) => sortOrder.indexOf(a) - sortOrder.indexOf(b)
)
```

**Comment by adam-coster** [comment]
Perfect!
